[colors]
[[colors.indexed_colors]]
index = 16
color = "#cba6f7"

[[colors.indexed_colors]]
index = 17
color = "#F5E0DC"

[colors.primary]
background = "#1E1E2E"
foreground = "#CDD6F4"
dim_foreground = "#CDD6F4"
bright_foreground = "#CDD6F4"

[colors.cursor]
text = "#1E1E2E"
cursor = "#F5E0DC"

[colors.vi_mode_cursor]
text = "#1E1E2E"
cursor = "#B4BEFE"

[colors.footer_bar]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.selection]
text = "#1E1E2E"
background = "#F5E0DC"

[colors.normal]
black = "#cba6f7"
red = "#cba6f7"
green = "#cba6f7"
yellow = "#cba6f7"
blue = "#cba6f7"
magenta = "#cba6f7"
cyan = "#cba6f7"
white = "#cba6f7"

[colors.bright]
black = "#cba6f7"
red = "#cba6f7"
green = "#cba6f7"
yellow = "#cba6f7"
blue = "#cba6f7"
magenta = "#cba6f7"
cyan = "#cba6f7"
white = "#cba6f7"

[colors.dim]
black = "#cba6f7"
red = "#cba6f7"
green = "#cba6f7"
yellow = "#cba6f7"
blue = "#cba6f7"
magenta = "#cba6f7"
cyan = "#cba6f7"
white = "#cba6f7"

[colors.search.matches]
foreground = "#1E1E2E"
background = "#A6ADC8"

[colors.search.focused_match]
foreground = "#1E1E2E"
background = "#A6E3A1"

[colors.hints.start]
foreground = "#1E1E2E"
background = "#F9E2AF"

[colors.hints.end]
foreground = "#1E1E2E"
background = "#A6ADC8"
